[package]
name = "env-sync"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.225", features = ["derive"], optional = true }
thiserror = "2.0.16"

[features]
default = []
serde = ["dep:serde"]
